from .resume_prompts import RESUME_ANALYSIS_PROMPT, SKILL_EXTRACTION_PROMPT
from .interview_prompts import QUESTION_GENERATION_PROMPT, MOCK_INTERVIEW_SYSTEM_PROMPT
from .feedback_prompts import FEEDBACK_PROMPT, OVERALL_FEEDBACK_PROMPT, ROADMAP_PROMPT
from .roadmap_prompts import SKILL_GAP_PROMPT

__all__ = [
    "RESUME_ANALYSIS_PROMPT",
    "SKILL_EXTRACTION_PROMPT",
    "QUESTION_GENERATION_PROMPT",
    "MOCK_INTERVIEW_SYSTEM_PROMPT",
    "FEEDBACK_PROMPT",
    "OVERALL_FEEDBACK_PROMPT",
    "ROADMAP_PROMPT",
    "SKILL_GAP_PROMPT",
]
